### ISSUE TITLE
Typo in import statement!

### ISSUE THREAD

**Issue by xpacman** [ivanzusko/react-bubble-preloader#2]
Hello! You have a typo in Usage section on your site. It says "react-bubble-peloader". Took me 5 minutes to get things to work :P 

Besides, thanks for making this nice preloader.

Have a nice day!

**Comment by ivanzusko** [comment]
Thank you for pointing that out @xpacman and my sincerely apologies that it took me 7 years to fix that 😞 

I hope you are doing well and I wish all the best 🤝
